name: Deploy Bio Scout

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js (if your project uses it)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      # Step 3: Install dependencies (if applicable)
      - name: Install dependencies
        run: npm install

      # Step 4: Run your build script (optional, if needed)
      - name: Build project
        run: npm run build

      # Step 5: Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bio-scout-artifact
          path: ./path-to-your-artifact

      # Step 6: Deploy step or additional tasks (add as necessary)
